
# Sets the following variables

# SDL2_IMAGE_LIBRARY, the name of the library to link against
# SDL2_IMAGE_FOUND, if false, do not try to link to SDL2
# SDL2_IMAGE_INCLUDE_DIR, where to find SDL.h



SET(SDL2_IMAGE_SEARCH_DIRS
	"./libs/SDL2_image"
	"${CMAKE_CURRENT_SOURCE_DIR}/libs/include"
	"${CMAKE_CURRENT_SOURCE_DIR}/libs/SDL2_IMAGE"
	"/usr/include"
	"/usr"
	"/usr/local/include"
	"/opt"
	"/Library/Frameworks"
	"~/Library/Frameworks"
	)

# check environment variable
SET(_SDL2_IMAGE_ENV_ROOT_DIR "$ENV{SDL2_IMAGE_ROOT_DIR}")

# set SDL2 ROOT if needed
IF(NOT SDL2_IMAGE_ROOT_DIR AND _SDL2_IMAGE_ENV_ROOT_DIR)
    SET(SDL2_IMAGE_ROOT_DIR "${_SDL2_IMAGE_ENV_ROOT_DIR}")
ENDIF(NOT SDL2_IMAGE_ROOT_DIR AND _SDL2_IMAGE_ENV_ROOT_DIR)

IF(SDL2_IMAGE_ROOT_DIR)
    SET(_SDL2_IMAGE_HEADER_SEARCH_DIRS "${SDL2_IMAGE_ROOT_DIR}"
                                "${SDL2_IMAGE_ROOT_DIR}"
                                 ${SDL2_IMAGE_SEARCH_DIRS})
ENDIF(SDL2_IMAGE_ROOT_DIR)

FIND_PATH(SDL2_IMAGE_INCLUDE_DIR
		SDL_image.h
		SDL2_image/SDL.h
		${SDL2_IMAGE_SEARCH_DIRS}/include 
		DOC "SDL2_IMAGE include directory"
)

FIND_LIBRARY(SDL2_IMAGE_LIBRARY
	NAMES	SDL2_image SDL2_image
	PATHS	${SDL2_IMAGE_SEARCH_DIRS}
	PATH_SUFFIXES
		lib
		lib64
		lib/x86
		lib/x64
	DOC "SDL2_IMAGE library"
)

IF (SDL2_IMAGE_INCLUDE_DIR AND SDL2_IMAGE_LIBRARY )
	SET(SDL2_IMAGE_FOUND TRUE )
	MESSAGE(STATUS "SDL2_IMAGE_INCLUDE_DIR = ${SDL2_IMAGE_INCLUDE_DIR}")
ELSE ( SDL2_IMAGE_INCLUDE_DIR AND SDL2_IMAGE_LIBRARY )
	SET( SDL2_IMAGE_FOUND FALSE )
	MESSAGE(STATUS "SDL2_IMAGE not found")
ENDIF ( SDL2_IMAGE_INCLUDE_DIR AND SDL2_IMAGE_LIBRARY )